### PR TITLE
This installs ChimeraX 1.2.5

### PR DESCRIPTION
**Pull request by pconesa**
It will not install it by default.

### CODE REVIEW

**Comment by rmarabini** [comment]
OK, I am trying this

**Review by rmarabini — APPROVED** [review]
The plugin works but I have found a "feature" that I do not like. 
In my installation chimera_home is not defined so the default CHIMERA_HOME is used.
I need to modify manually 3 lines of code to make this work, 2 in scipion-em-chimera

cls._defineEmVar(CHIMERA_HOME, 'chimerax-1.1')            
 cls.defineChimeraXInstallation(env, V-1.1, default=True, tarDir='chimera_1.1.tar.gz']);

and another line in 

 scipion-em

../../scipion3/scipion-em/pwem/__init__.py:    CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax-1.1')))

It would be grate if scipion could retrieve the chimera path from scipion-em-chimera. 
I tried to implement it but I do not see an easy way since chimera Plugin is, in general,. installed after pwem and therefore is not available.

**Comment by pconesa** [comment]
Yes, this one is a tricky one. Changing values in the plugin is normal in a "new release" installation". The one in pwem, its tricky.

**Comment by rmarabini** [comment]
Hi @pconesa,

 We may go ahead and  merge but then scipion-em line 

`../../scipion3/scipion-em/pwem/init.py: CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax-1.1')))
`
should be updated.

I would suggest two changes in scipion-em

1) change 

 `../../scipion3/scipion-em/pwem/init.py: CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax-1.1')))
`

by

 `../../scipion3/scipion-em/pwem/init.py: CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax')))
`

2) change

Store the chimera version that scipion needs as a constant in scipion-em and if scipion-em-chimera has been created for a later version at least it can check and complain about it. So far I think chimera 1.2 supports all functions defined in chimera 1.1

**Comment by rmarabini** [comment]
Hi @pconesa,

   What should I do with this PR? I may merge it but scipion-em needs to be updated so the line

scipion3/scipion-em/pwem/init.py: CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax-1.1')))

points to the right directory.

I think a default value of:

../../scipion3/scipion-em/pwem/init.py: CHIMERA_HOME = _join(_get('CHIMERA_HOME', os.path.join(EM_ROOT, 'chimerax'))) 

will be the right way to go.

**Comment by pconesa** [comment]
Can you leave it there until we both are back?

**Comment by rmarabini** [comment]
vale.

**Pull request merged**
