### PR TITLE
Hot fix of tk-html-widgets package installation.

### PR DESCRIPTION
**Pull request by pconesa**
THis should fix the installation problem of tk-html-widgets package.

### CODE REVIEW

**Comment by pconesa** [comment]
Closes #92

**Review by rmarabini — APPROVED** [review]

**Comment by rmarabini** [comment]
It works in my computer ;-)

**Comment by rmarabini** [comment]
Hi @pconesa ,

    Something went wrong in pypi

25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Invalid value for requires_dist. Error: Can't have direct dependency:  
         'tk-html-widgets @                                                     
         git+https://github.com/***-em/tk_html_widgets@master'              
Error: Process completed with exit code 1.

=====


deploy
failed Jul 18, 2023 in 2m 34s
3s
1s
37s
0s
1m 49s
2s
Run python setup.py sdist bdist_wheel
running sdist
running egg_info
creating ***_em_chimera.egg-info
writing ***_em_chimera.egg-info/PKG-INFO
writing dependency_links to ***_em_chimera.egg-info/dependency_links.txt
writing entry points to ***_em_chimera.egg-info/entry_points.txt
writing requirements to ***_em_chimera.egg-info/requires.txt
writing top-level names to ***_em_chimera.egg-info/top_level.txt
writing manifest file '***_em_chimera.egg-info/SOURCES.txt'
adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
reading manifest file '***_em_chimera.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file '***_em_chimera.egg-info/SOURCES.txt'
running check
creating ***-em-chimera-3.3.6
creating ***-em-chimera-3.3.6/chimera
creating ***-em-chimera-3.3.6/chimera/Bundles
creating ***-em-chimera-3.3.6/chimera/Bundles/***
creating ***-em-chimera-3.3.6/chimera/Bundles/***/src
creating ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs
creating ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user
creating ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
creating ***-em-chimera-3.3.6/chimera/colabs
creating ***-em-chimera-3.3.6/chimera/protocols
creating ***-em-chimera-3.3.6/chimera/tests
creating ***-em-chimera-3.3.6/chimera/viewers
creating ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying files to ***-em-chimera-3.3.6...
copying CHANGES.txt -> ***-em-chimera-3.3.6
copying FAQ.rst -> ***-em-chimera-3.3.6
copying LICENSE -> ***-em-chimera-3.3.6
copying MANIFEST.in -> ***-em-chimera-3.3.6
copying README.rst -> ***-em-chimera-3.3.6
copying requirements.txt -> ***-em-chimera-3.3.6
copying setup.py -> ***-em-chimera-3.3.6
copying chimera/__init__.py -> ***-em-chimera-3.3.6/chimera
copying chimera/bibtex.py -> ***-em-chimera-3.3.6/chimera
copying chimera/constants.py -> ***-em-chimera-3.3.6/chimera
copying chimera/convert.py -> ***-em-chimera-3.3.6/chimera
copying chimera/editList.py -> ***-em-chimera-3.3.6/chimera
copying chimera/getchimera.py -> ***-em-chimera-3.3.6/chimera
copying chimera/objects.py -> ***-em-chimera-3.3.6/chimera
copying chimera/parser_h1.py -> ***-em-chimera-3.3.6/chimera
copying chimera/protocols.conf -> ***-em-chimera-3.3.6/chimera
copying chimera/utils.py -> ***-em-chimera-3.3.6/chimera
copying chimera/wizards.py -> ***-em-chimera-3.3.6/chimera
copying chimera/Bundles/***/bundle_info.xml -> ***-em-chimera-3.3.6/chimera/Bundles/***
copying chimera/Bundles/***/src/__init__.py -> ***-em-chimera-3.3.6/chimera/Bundles/***/src
copying chimera/Bundles/***/src/api.py -> ***-em-chimera-3.3.6/chimera/Bundles/***/src
copying chimera/Bundles/***/src/cmd.py -> ***-em-chimera-3.3.6/chimera/Bundles/***/src
copying chimera/Bundles/***/src/constants.py -> ***-em-chimera-3.3.6/chimera/Bundles/***/src
copying chimera/Bundles/***/src/docs/user/commands/***.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***combine.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***rs.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***shell.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***shellcrown.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***ss.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***write.html -> ***-em-chimera-3.3.6/chimera/Bundles/***/src/docs/user/commands
copying chimera/colabs/browser.py -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/chimera_alphafold21_colab.ipynb -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/chimera_alphafold_colab.ipynb -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/click.py -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/down.py -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/kk.colab -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/kk.ipynb -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/mouse.py -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/phenix_alphafold_colab.ipynb -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/colabs/test_colab.ipynb -> ***-em-chimera-3.3.6/chimera/colabs
copying chimera/protocols/__init__.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_alphafold.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_base.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_contacts.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_fit.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_modeller_search.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_operate.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_restore.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/protocols/protocol_subtraction_maps.py -> ***-em-chimera-3.3.6/chimera/protocols
copying chimera/tests/__init__.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_alpha_fold.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_objects.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_protocol_chimera_fit.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_protocol_chimera_map_subtraction.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_protocol_chimera_operate.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_protocol_contact.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/tests/test_protocol_modeller_search.py -> ***-em-chimera-3.3.6/chimera/tests
copying chimera/viewers/__init__.py -> ***-em-chimera-3.3.6/chimera/viewers
copying chimera/viewers/viewer.py -> ***-em-chimera-3.3.6/chimera/viewers
copying chimera/viewers/viewer_contacts.py -> ***-em-chimera-3.3.6/chimera/viewers
copying ***_em_chimera.egg-info/PKG-INFO -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying ***_em_chimera.egg-info/SOURCES.txt -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying ***_em_chimera.egg-info/dependency_links.txt -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying ***_em_chimera.egg-info/entry_points.txt -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying ***_em_chimera.egg-info/requires.txt -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
copying ***_em_chimera.egg-info/top_level.txt -> ***-em-chimera-3.3.6/***_em_chimera.egg-info
Writing ***-em-chimera-3.3.6/setup.cfg
creating dist
Creating tar archive
removing '***-em-chimera-3.3.6' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/chimera
copying chimera/bibtex.py -> build/lib/chimera
copying chimera/editList.py -> build/lib/chimera
copying chimera/objects.py -> build/lib/chimera
copying chimera/convert.py -> build/lib/chimera
copying chimera/utils.py -> build/lib/chimera
copying chimera/getchimera.py -> build/lib/chimera
copying chimera/__init__.py -> build/lib/chimera
copying chimera/parser_h1.py -> build/lib/chimera
copying chimera/wizards.py -> build/lib/chimera
copying chimera/constants.py -> build/lib/chimera
creating build/lib/chimera/viewers
copying chimera/viewers/viewer_contacts.py -> build/lib/chimera/viewers
copying chimera/viewers/__init__.py -> build/lib/chimera/viewers
copying chimera/viewers/viewer.py -> build/lib/chimera/viewers
creating build/lib/chimera/protocols
copying chimera/protocols/protocol_fit.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_restore.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_operate.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_contacts.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_modeller_search.py -> build/lib/chimera/protocols
copying chimera/protocols/__init__.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_base.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_subtraction_maps.py -> build/lib/chimera/protocols
copying chimera/protocols/protocol_alphafold.py -> build/lib/chimera/protocols
creating build/lib/chimera/tests
copying chimera/tests/test_protocol_chimera_operate.py -> build/lib/chimera/tests
copying chimera/tests/test_objects.py -> build/lib/chimera/tests
copying chimera/tests/test_alpha_fold.py -> build/lib/chimera/tests
copying chimera/tests/test_protocol_modeller_search.py -> build/lib/chimera/tests
copying chimera/tests/test_protocol_chimera_map_subtraction.py -> build/lib/chimera/tests
copying chimera/tests/test_protocol_chimera_fit.py -> build/lib/chimera/tests
copying chimera/tests/test_protocol_contact.py -> build/lib/chimera/tests
copying chimera/tests/__init__.py -> build/lib/chimera/tests
copying chimera/protocols.conf -> build/lib/chimera
creating build/lib/chimera/Bundles
creating build/lib/chimera/Bundles/***
copying chimera/Bundles/***/bundle_info.xml -> build/lib/chimera/Bundles/***
creating build/lib/chimera/Bundles/***/src
copying chimera/Bundles/***/src/__init__.py -> build/lib/chimera/Bundles/***/src
copying chimera/Bundles/***/src/api.py -> build/lib/chimera/Bundles/***/src
copying chimera/Bundles/***/src/cmd.py -> build/lib/chimera/Bundles/***/src
copying chimera/Bundles/***/src/constants.py -> build/lib/chimera/Bundles/***/src
creating build/lib/chimera/Bundles/***/src/docs
creating build/lib/chimera/Bundles/***/src/docs/user
creating build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***combine.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***rs.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***shell.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***shellcrown.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***ss.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
copying chimera/Bundles/***/src/docs/user/commands/***write.html -> build/lib/chimera/Bundles/***/src/docs/user/commands
creating build/lib/chimera/colabs
copying chimera/colabs/browser.py -> build/lib/chimera/colabs
copying chimera/colabs/chimera_alphafold21_colab.ipynb -> build/lib/chimera/colabs
copying chimera/colabs/chimera_alphafold_colab.ipynb -> build/lib/chimera/colabs
copying chimera/colabs/click.py -> build/lib/chimera/colabs
copying chimera/colabs/down.py -> build/lib/chimera/colabs
copying chimera/colabs/kk.colab -> build/lib/chimera/colabs
copying chimera/colabs/kk.ipynb -> build/lib/chimera/colabs
copying chimera/colabs/mouse.py -> build/lib/chimera/colabs
copying chimera/colabs/phenix_alphafold_colab.ipynb -> build/lib/chimera/colabs
copying chimera/colabs/test_colab.ipynb -> build/lib/chimera/colabs
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/bibtex.py -> build/bdist.linux-x86_64/wheel/chimera
creating build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/phenix_alphafold_colab.ipynb -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/kk.ipynb -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/mouse.py -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/chimera_alphafold_colab.ipynb -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/down.py -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/click.py -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/test_colab.ipynb -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/chimera_alphafold21_colab.ipynb -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/kk.colab -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/colabs/browser.py -> build/bdist.linux-x86_64/wheel/chimera/colabs
copying build/lib/chimera/editList.py -> build/bdist.linux-x86_64/wheel/chimera
creating build/bdist.linux-x86_64/wheel/chimera/viewers
copying build/lib/chimera/viewers/viewer_contacts.py -> build/bdist.linux-x86_64/wheel/chimera/viewers
copying build/lib/chimera/viewers/__init__.py -> build/bdist.linux-x86_64/wheel/chimera/viewers
copying build/lib/chimera/viewers/viewer.py -> build/bdist.linux-x86_64/wheel/chimera/viewers
copying build/lib/chimera/objects.py -> build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/protocols.conf -> build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/convert.py -> build/bdist.linux-x86_64/wheel/chimera
creating build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_fit.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_restore.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_operate.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_contacts.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_modeller_search.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/__init__.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_base.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_subtraction_maps.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/protocols/protocol_alphafold.py -> build/bdist.linux-x86_64/wheel/chimera/protocols
copying build/lib/chimera/utils.py -> build/bdist.linux-x86_64/wheel/chimera
creating build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_protocol_chimera_operate.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_objects.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_alpha_fold.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_protocol_modeller_search.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_protocol_chimera_map_subtraction.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_protocol_chimera_fit.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/test_protocol_contact.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/tests/__init__.py -> build/bdist.linux-x86_64/wheel/chimera/tests
copying build/lib/chimera/getchimera.py -> build/bdist.linux-x86_64/wheel/chimera
creating build/bdist.linux-x86_64/wheel/chimera/Bundles
creating build/bdist.linux-x86_64/wheel/chimera/Bundles/***
copying build/lib/chimera/Bundles/***/bundle_info.xml -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***
creating build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src
copying build/lib/chimera/Bundles/***/src/api.py -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src
creating build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs
creating build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user
creating build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***write.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***rs.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***shellcrown.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***combine.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***ss.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/docs/user/commands/***shell.html -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src/docs/user/commands
copying build/lib/chimera/Bundles/***/src/cmd.py -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src
copying build/lib/chimera/Bundles/***/src/__init__.py -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src
copying build/lib/chimera/Bundles/***/src/constants.py -> build/bdist.linux-x86_64/wheel/chimera/Bundles/***/src
copying build/lib/chimera/__init__.py -> build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/parser_h1.py -> build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/wizards.py -> build/bdist.linux-x86_64/wheel/chimera
copying build/lib/chimera/constants.py -> build/bdist.linux-x86_64/wheel/chimera
running install_egg_info
Copying ***_em_chimera.egg-info to build/bdist.linux-x86_64/wheel/***_em_chimera-3.3.6-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/***_em_chimera-3.3.6.dist-info/WHEEL
creating 'dist/***_em_chimera-3.3.6-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'chimera/__init__.py'
adding 'chimera/bibtex.py'
adding 'chimera/constants.py'
adding 'chimera/convert.py'
adding 'chimera/editList.py'
adding 'chimera/getchimera.py'
adding 'chimera/objects.py'
adding 'chimera/parser_h1.py'
adding 'chimera/protocols.conf'
adding 'chimera/utils.py'
adding 'chimera/wizards.py'
adding 'chimera/Bundles/***/bundle_info.xml'
adding 'chimera/Bundles/***/src/__init__.py'
adding 'chimera/Bundles/***/src/api.py'
adding 'chimera/Bundles/***/src/cmd.py'
adding 'chimera/Bundles/***/src/constants.py'
adding 'chimera/Bundles/***/src/docs/user/commands/***.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***combine.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***rs.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***shell.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***shellcrown.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***ss.html'
adding 'chimera/Bundles/***/src/docs/user/commands/***write.html'
adding 'chimera/colabs/browser.py'
adding 'chimera/colabs/chimera_alphafold21_colab.ipynb'
adding 'chimera/colabs/chimera_alphafold_colab.ipynb'
adding 'chimera/colabs/click.py'
adding 'chimera/colabs/down.py'
adding 'chimera/colabs/kk.colab'
adding 'chimera/colabs/kk.ipynb'
adding 'chimera/colabs/mouse.py'
adding 'chimera/colabs/phenix_alphafold_colab.ipynb'
adding 'chimera/colabs/test_colab.ipynb'
adding 'chimera/protocols/__init__.py'
adding 'chimera/protocols/protocol_alphafold.py'
adding 'chimera/protocols/protocol_base.py'
adding 'chimera/protocols/protocol_contacts.py'
adding 'chimera/protocols/protocol_fit.py'
adding 'chimera/protocols/protocol_modeller_search.py'
adding 'chimera/protocols/protocol_operate.py'
adding 'chimera/protocols/protocol_restore.py'
adding 'chimera/protocols/protocol_subtraction_maps.py'
adding 'chimera/tests/__init__.py'
adding 'chimera/tests/test_alpha_fold.py'
adding 'chimera/tests/test_objects.py'
adding 'chimera/tests/test_protocol_chimera_fit.py'
adding 'chimera/tests/test_protocol_chimera_map_subtraction.py'
adding 'chimera/tests/test_protocol_chimera_operate.py'
adding 'chimera/tests/test_protocol_contact.py'
adding 'chimera/tests/test_protocol_modeller_search.py'
adding 'chimera/viewers/__init__.py'
adding 'chimera/viewers/viewer.py'
adding 'chimera/viewers/viewer_contacts.py'
adding '***_em_chimera-3.3.6.dist-info/LICENSE'
adding '***_em_chimera-3.3.6.dist-info/METADATA'
adding '***_em_chimera-3.3.6.dist-info/WHEEL'
adding '***_em_chimera-3.3.6.dist-info/entry_points.txt'
adding '***_em_chimera-3.3.6.dist-info/top_level.txt'
adding '***_em_chimera-3.3.6.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ***_em_chimera-3.3.6-py3-none-any.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/171.1 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/171.1 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/171.1 kB • --:-- • ?
 48% ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 81.9/171.1 kB • 00:01 • 107.1 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.1/171.1 kB • 00:00 • 2.2 MB/s
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Invalid value for requires_dist. Error: Can't have direct dependency:  
         'tk-html-widgets @                                                     
         git+https://github.com/***-em/tk_html_widgets@master'              
Error: Process completed with exit code 1.

**Comment by pconesa** [comment]
It seems pypi does not like the syntax.

I've made a different approach. That also worked for me but does not send the dependency to pypi.

**Pull request merged**
